const transcript = document.querySelector('#transcript'); const chat = document.querySelector('#chat'); const query = document.querySelector('#query'); const status = document.querySelector('#status'); let currentResponse; let currentTab; let currentVideoTimeSec = 0;
const timeLabel = (seconds) => { const total = Math.floor(seconds || 0); return `${Math.floor(total / 60)}:${String(total % 60).padStart(2, '0')}`; };
function addChunk(chunk) { let row = document.querySelector(`[data-chunk-id="${chunk.id}"]`); if (!row) { row = document.createElement('div'); row.className = 'line'; row.dataset.chunkId = chunk.id; transcript.append(row); } row.innerHTML = `<span class="time">[${timeLabel(chunk.startTime)}]</span>${chunk.text}`; row.querySelector('.time').onclick = () => currentTab && chrome.tabs.sendMessage(currentTab.id, { type: 'SEEK_VIDEO', time: chunk.startTime }); transcript.scrollTop = transcript.scrollHeight; }
function addMessage(role, text, meta = '') { const node = document.createElement('div'); node.className = `message ${role}`; node.innerHTML = `<div>${text}</div>${meta ? `<div class="meta">${meta}</div>` : ''}`; chat.append(node); chat.scrollTop = chat.scrollHeight; return node; }
async function getTab() { const tabs = await chrome.tabs.query({ active: true, currentWindow: true }); currentTab = tabs[0]; return currentTab; }
document.querySelector('#start').onclick = async () => { const tab = await getTab(); const result = await chrome.runtime.sendMessage({ type: 'START_TRANSCRIPTION', tabId: tab.id, videoTitle: tab.title, videoUrl: tab.url }); if (result?.error) { status.textContent = 'Unavailable'; addMessage('assistant', result.error); return; } status.textContent = 'Listening'; };
document.querySelector('#stop').onclick = async () => { await chrome.runtime.sendMessage({ type: 'STOP_TRANSCRIPTION' }); status.textContent = 'Stopped'; };
document.querySelector('#clear').onclick = async () => { await chrome.runtime.sendMessage({ type: 'CLEAR_TRANSCRIPT' }); transcript.replaceChildren(); };
document.querySelector('#settings').onclick = () => chrome.runtime.openOptionsPage();
async function submit(text) { if (!text.trim()) return; addMessage('user', text); query.value = ''; currentResponse = addMessage('assistant', ''); status.textContent = 'Thinking'; await chrome.runtime.sendMessage({ type: 'USER_QUERY', query: text, currentVideoTimeSec }); }
document.querySelector('#query-form').onsubmit = (event) => { event.preventDefault(); submit(query.value); }; document.querySelectorAll('[data-query]').forEach((button) => button.onclick = () => submit(button.dataset.query));
chrome.runtime.onMessage.addListener((message) => { if (message.type === 'VIDEO_TIME_UPDATE') currentVideoTimeSec = message.currentTimeSec; if (message.type === 'LISTENING_STARTED') status.textContent = 'Listening'; if (message.type === 'LISTENING_STOPPED') status.textContent = 'Stopped'; if (message.type === 'TRANSCRIPT_UPDATE') addChunk(message.chunk); if (message.type === 'TRANSCRIPT_REPLACE') { transcript.replaceChildren(); message.chunks.forEach(addChunk); status.textContent = 'Captions loaded'; } if (message.type === 'LLM_TOKEN') currentResponse?.firstElementChild && (currentResponse.firstElementChild.textContent += message.token); if (message.type === 'LLM_DONE') { status.textContent = 'Ready'; if (message.contextMeta) currentResponse?.insertAdjacentHTML('beforeend', `<div class="meta">${message.contextMeta.chunkCount} transcript chunks used</div>`); } if (message.type === 'ERROR') { status.textContent = 'Unavailable'; addMessage('assistant', message.message); } });
(async () => { const state = await chrome.runtime.sendMessage({ type: 'GET_TRANSCRIPT' }); state?.chunks?.forEach(addChunk); })();
