let video; let lastTime = -1;
function findVideo() { return document.querySelector('video'); }
function wireVideo() { video = findVideo(); if (!video || video.dataset.studyPartnerWired) return; video.dataset.studyPartnerWired = 'true'; video.addEventListener('timeupdate', () => { if (Math.abs(video.currentTime - lastTime) >= 1) { lastTime = video.currentTime; chrome.runtime.sendMessage({ type: 'VIDEO_TIME_UPDATE', currentTimeSec: video.currentTime }); } }); chrome.runtime.sendMessage({ type: 'VIDEO_TIME_UPDATE', currentTimeSec: video.currentTime }); }
function sendCaptions() { if (!video) return; [...video.textTracks].forEach((track) => { track.mode = 'hidden'; }); const chunks = [...video.textTracks].flatMap((track) => [...(track.cues || [])].map((cue, index) => ({ id: `caption_${track.language || 'default'}_${index}_${cue.startTime}`, startTime: cue.startTime, endTime: cue.endTime, text: cue.text.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim(), source: 'captions', isFinal: true }))).filter((chunk) => chunk.text); if (chunks.length) chrome.runtime.sendMessage({ type: 'CAPTIONS_FOUND', chunks }); }
async function sendYoutubeCaptions() { if (!location.hostname.includes('youtube.com')) return; const response = window.ytInitialPlayerResponse || [...document.scripts].map((script) => script.textContent.match(/ytInitialPlayerResponse\s*=\s*(\{.*?\});/s)?.[1]).filter(Boolean).map((text) => { try { return JSON.parse(text); } catch { return null; } }).find(Boolean); const tracks = response?.captions?.playerCaptionsTracklistRenderer?.captionTracks; const track = tracks?.find((item) => item.languageCode === navigator.language.split('-')[0]) || tracks?.[0]; if (!track?.baseUrl) return; try { const xml = await (await fetch(track.baseUrl)).text(); const chunks = [...new DOMParser().parseFromString(xml, 'text/xml').querySelectorAll('text')].map((cue, index) => { const startTime = Number(cue.getAttribute('start') || 0); const duration = Number(cue.getAttribute('dur') || 1); return { id: `youtube_caption_${index}_${startTime}`, startTime, endTime: startTime + duration, text: cue.textContent.replace(/\s+/g, ' ').trim(), source: 'captions', isFinal: true }; }).filter((chunk) => chunk.text); if (chunks.length) chrome.runtime.sendMessage({ type: 'CAPTIONS_FOUND', chunks }); } catch (error) { chrome.runtime.sendMessage({ type: 'ERROR', message: `Could not load YouTube captions: ${error.message}` }); } }
wireVideo(); new MutationObserver(wireVideo).observe(document.documentElement, { childList: true, subtree: true });
setTimeout(sendCaptions, 1000);
setTimeout(sendYoutubeCaptions, 1500);
chrome.runtime.onMessage.addListener((message) => { if (!video) video = findVideo(); if (message.type === 'PAUSE_VIDEO') video?.pause(); if (message.type === 'RESUME_VIDEO') video?.play().catch(() => {}); if (message.type === 'SEEK_VIDEO' && video) video.currentTime = message.time; });
